// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BaseModal: typeof import("./../src/components/BaseComponents/BaseModal/index.vue")["default"];
    HelloWorld: typeof import("./../src/components/BusinessComponents/HelloWorld/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    Toast: typeof import("./../src/components/BaseComponents/Toast/index.vue")["default"];
    VanButton: typeof import("vant/es")["Button"];
  }
}

export {};
